spring.main.banner-mode=off

# DataSource
spring.datasource.url=jdbc:hsqldb:file:/usr/local/sites/financedb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

# Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

#Thymeleaf disable cache
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vuktx1979@gmail.com
spring.mail.password=thaivudn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.enable = true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.fallback = false

server.port = 8090
server.session.timeout=3600

#Facebook tradealert
#spring.social.facebook.appId=197313220811602
#spring.social.facebook.appSecret=ffe6beabac61fd640c45390209993422

#Facebook tradealert Test version
spring.social.facebook.appId=505332969835325
spring.social.facebook.appSecret=05b9bc0a55588ab85ad1352ccee247c9

