spring.main.banner-mode=off
################hsqldb Configuration###########################
spring.datasource.url=jdbc:hsqldb:file:/Users/vutran/Projects/db/financedb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
################mysql Configuration###########################
#spring.datasource.url=jdbc:mysql://localhost:3306/finance?useUnicode=true&amp;characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.url=jdbc:mysql://192.168.2.3:3306/finance?useUnicode=true&amp;characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=TranQuang2007
#spring.datasource.url=jdbc:mysql://www.db4free.net:3306/finance?useUnicode=true&amp;characterEncoding=UTF-8
#spring.datasource.username=cuoi5s
#spring.datasource.password=TranQuang2007
#spring.datasource.url=jdbc:mysql://cuoi5s.cxdk077pos3m.us-east-1.rds.amazonaws.com:3306/cuoi5s?useUnicode=true&amp;characterEncoding=UTF-8
#spring.datasource.username=cuoi5s
#spring.datasource.password=TranQuang2007
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
################ Number of ms to wait before throwing an exception if no connection is available.###############
spring.datasource.tomcat.max-wait=10000
################ Maximum number of active connections that can be allocated from this pool at the same time.
spring.datasource.tomcat.max-active=50
################ Validate the connection before borrowing it from the pool.
spring.datasource.tomcat.test-on-borrow=true
################  Hibernate #########################################################################################
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
#Hibernate log
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
# Naming strategy
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#Thymeleaf disable cache
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
################Email Configuration###########################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartandhappytrading@gmail.com
spring.mail.password=Pan2c010
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.enable = true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.fallback = false
################Facebook Configuration###########################
#Facebook tradealert
#spring.social.facebook.appId=197313220811602
#spring.social.facebook.appSecret=ffe6beabac61fd640c45390209993422
#Facebook tradealert Test version
spring.social.facebook.appId=505332969835325
spring.social.facebook.appSecret=05b9bc0a55588ab85ad1352ccee247c9
################Json format as string Configuration###########################
spring.jackson.serialization.write_dates_as_timestamps=false
################ehcache#################################################
spring.cache.jcache.config=classpath:ehcache.xml

################SSL#################################################
#https://www.thomasvitale.com/https-spring-boot-ssl-certificate/
server.port=443
server.ssl.key-store=/Users/vutran/Projects/finance/springboot.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

################Session#################################################
server.session.timeout=3600

################TD Ameritrade configuration#################################################
td.access-token=Bearer PtLS7b9vKbAdJFhFMHFbGOENSluJT8eDumFVBhURSHPKR6FjhQhtk81aX2WGP2rSF2StdPLpKWkz6yTQ/91P5ZraFJ4b94TVCp2ZRzwC3GvGRkR+tYSHar/e164eKz+w0MW10swrF+uBVpQUkIEO/X71lZ2c4ZhhMaHNx7DDmV5QNT3Uu2gXtgnF+rerlgtCVTOWO02Nc2rS/uTLUx83x4NgE0nWoodVORGgUirvko47se0Awbmf6LfwSiX8XbKDah73yEqpNh0RPNpxoyk6gzkkVTDyqsXIakHUrxFT9O7uFOxvEuyGRAB7WmGAkRsv2d4KreKKEeJEccZPbRkbaYIpbU+X6D2QS07ZkArm9tWyPx4RtuT+TGXcfRXR+TslWQ6lpXzs1ZVvZnpl98bOJxVoSW9CvJVvZJctaqYulri6+vkTCFX+LvHy1nOvAB/kKKYkfHNkm0exRlK4F20of7fy7Fu4asEGPwX/SUiiG/KnRnt6cRjsX6ZRVapRIFxaNr/9+uSAz+iZS7p0bmVNNXlZtGbj7+aor/0QnbDZAraJu+hP7a+ms8dkxOPTzkolVyW5jVmH/BU/HF09F100MQuG4LYrgoVi/JHHvlWoCrQZauHhlGiyN40KtCdzAuMEAC159kRdnuBNlhnydJzyqSR0k9r3w7os3Nk8d8fsOlyWX6LzaSZwxSS6eSjT+5HllfRjVSnpL/9L+5ECfOu17Ifwia2dfdZHqFVKL2elo1ZwtBo8AhZUaj4+Hr6yAC8WG8y4WGJoqtVpGSnG2MNt7G6pDjxReA5JqGBFVVsl8Wgg4MkxW2YNmT0yZYdDKfVXVoXJTng1mtAKGTuckkdLs8oKKVHVloOSjhdH/QoQZyv+gCe20yDCKF0MUo1OPEYZ89rodTeLRu7PYzUF7lbRPkePwlh4SWQ3mIN5KcdiItQ05BSXRwYe/sjtGGQcTkM4a8dFCDzoxDZm3S2HShUkhvhR2AA/0FW8FZkwD9U3AEDk+k7Y9YL5uuBUNlsDGCd2DpEesx/Vjth5feZeDJlYkR6BKQQs2YM5Hp9AkkflfdTRYabnyky+RrexPAVxwJ7hslFoj9CNFh3bG/cyqe1RZvhG1y0JLvGt2+yhKHqS91oqxTPM4BMJOmAxXuh9CdNwzdUuY5yofkv4gwi/LXEEdYd5itBL7a16A3cSJecrheuYONUSA0JQYg==212FD3x19z9sWBHDJACbC00B75E
url=https://auth.tdameritrade.com/auth?response_type=code&redirect_uri=https://localhost/api/td/v1/callback&client_id=WKSETQUMDUZQGLHDYZHGRIG1L7JJ1WCB@AMER.OAUTHAP
td.app.callback=https://localhost/api/td/v1/callback
browser=Chrome

